"""
Financial Functions - Batch 7 (Equations 612-713)
"""
import numpy as np
import pandas as pd
from scipy import stats


def profit_factor(returns):
    '''
    domain: ['Performance measurement & attribution']
    subdomain: ['Risk-Adjusted Performance', 'Trading Performance']
    function: "Profit Factor measures the ratio of gross profits to gross losses over a given period. A profit factor greater than 1 indicates a profitable strategy, while a value below 1 indicates losses exceed gains. It is a widely used metric in evaluating trading system performance."
    y_as_x: []
    :param returns: "Returns are the gain or loss generated on an investment over a specific period, expressed as a time series of periodic returns (e.g., daily, monthly)."
    :return: "Computed Profit Factor = sum of positive returns / |sum of negative returns|"
    '''
    import quantstats as qs
    returns = pd.Series(returns)
    return qs.stats.profit_factor(returns)


def profitability_index(pv_future_cash_flows, initial_investment):
    '''
    domain: ['Corporate finance & capital budgeting']
    subdomain: ['Capital Budgeting', 'Investment Appraisal']
    function: "Profitability Index (PI) is a capital budgeting metric that measures the ratio of the present value of future expected cash flows to the initial investment. A PI greater than 1.0 indicates that the project's NPV is positive and the investment is value-creating. It is useful for ranking projects when capital is rationed."
    y_as_x: []
    :param pv_future_cash_flows: "Present value of future cash flows expected from the investment, discounted at the appropriate cost of capital."
    :param initial_investment: "The initial cash outlay required to undertake the project or investment."
    :return: "Computed Profitability Index = PV of future cash flows / Initial Investment"
    '''
    return pv_future_cash_flows / initial_investment


def property_irr(equity_invested, cash_flows, sale_proceeds):
    '''
    domain: ['Real estate finance & mortgages']
    subdomain: ['Real Estate Investment Analysis', 'Property Valuation']
    function: "Property IRR is the internal rate of return on a real estate investment, accounting for the initial equity invested, periodic operating cash flows, and the terminal sale proceeds. It is the discount rate that sets the net present value of all equity cash flows to zero."
    y_as_x: []
    :param equity_invested: "The initial equity capital contributed by the investor to acquire the property."
    :param cash_flows: "A list or array of periodic net operating cash flows (after debt service) received during the holding period."
    :param sale_proceeds: "The net proceeds from the sale of the property at the end of the holding period, after deducting transaction costs and remaining loan balance."
    :return: "Computed Property IRR such that 0 = -Equity_0 + sum_t CF_t/(1+IRR)^t + SaleProceeds/(1+IRR)^T"
    '''
    import numpy_financial as npf
    all_cfs = [-equity_invested] + list(cash_flows)
    all_cfs[-1] = all_cfs[-1] + sale_proceeds
    return npf.irr(all_cfs)


def property_value_from_cap_rate(net_operating_income_noi, capitalization_rate):
    '''
    domain: ['Real estate finance']
    subdomain: ['Property Valuation', 'Income Approach']
    function: "Property Value from Cap Rate computes the estimated market value of an income-producing property by dividing its net operating income by the capitalization rate. This is the income capitalization approach widely used in real estate appraisal."
    y_as_x: []
    :param net_operating_income_noi: "Net Operating Income (NOI) is the annual income generated by the property after deducting all operating expenses but before debt service and capital expenditures."
    :param capitalization_rate: "Capitalization Rate (Cap Rate) is the ratio of a property's NOI to its current market value, reflecting the expected rate of return on a real estate investment."
    :return: "Computed Property Value = NOI / Cap Rate"
    '''
    return net_operating_income_noi / capitalization_rate


def prospective_reserve(future_benefits_pv, future_premiums_pv):
    '''
    domain: ['Actuarial science & insurance']
    subdomain: ['Life Insurance Reserving', 'Policy Values']
    function: "Prospective Reserve (V_t) is the actuarial reserve at time t calculated as the present value of future benefits minus the present value of future premiums. It represents the amount the insurer must hold to cover future obligations net of expected future income from the policyholder."
    y_as_x: []
    :param future_benefits_pv: "Present value at time t of all future benefit payments expected under the insurance policy."
    :param future_premiums_pv: "Present value at time t of all future premium payments expected to be received from the policyholder."
    :return: "Computed Prospective Reserve V_t = PV_t(Future Benefits) - PV_t(Future Premiums)"
    '''
    return future_benefits_pv - future_premiums_pv


def protective_put_payoff(S_T, K, premium):
    '''
    domain: ['Derivatives, options & volatility']
    subdomain: ['Option Strategies', 'Hedging Strategies']
    function: "Protective Put Payoff is the net payoff from holding a long stock position combined with a long put option. This strategy provides downside protection by limiting the maximum loss to the premium paid plus the difference between the stock price and strike price. The payoff equals the stock price at expiry plus the put payoff minus the premium paid."
    y_as_x: []
    :param S_T: "The stock price at expiration of the option."
    :param K: "The strike price of the put option."
    :param premium: "The premium paid for the put option."
    :return: "Computed Protective Put Payoff = S_T + max(K - S_T, 0) - Premium"
    '''
    return S_T + np.maximum(K - S_T, 0) - premium


def provision_coverage_ratio(loan_loss_reserves, nonperforming_loans):
    '''
    domain: ['Bank regulation, Basel & prudential ratios']
    subdomain: ['Asset Quality', 'Prudential Ratios']
    function: "Provision Coverage Ratio measures the extent to which a bank's loan loss reserves cover its nonperforming loans. A higher ratio indicates greater preparedness for potential credit losses and stronger provisioning adequacy."
    y_as_x: []
    :param loan_loss_reserves: "The total allowance or reserves set aside by the bank to absorb expected losses on its loan portfolio."
    :param nonperforming_loans: "Loans that are in default or close to being in default, typically more than 90 days past due."
    :return: "Computed Provision Coverage Ratio = Loan Loss Reserves / Nonperforming Loans"
    '''
    return loan_loss_reserves / nonperforming_loans


def provision_coverage_ratio_v2(allowance_for_credit_losses, nonperforming_loans):
    '''
    domain: ['Banking, consumer lending & project finance']
    subdomain: ['Credit Risk Management', 'Asset Quality']
    function: "Provision Coverage Ratio (v2) measures the proportion of nonperforming loans covered by the allowance for credit losses (ACL). It indicates how well a bank is provisioned against potential credit losses from its nonperforming loan portfolio."
    y_as_x: []
    :param allowance_for_credit_losses: "The total allowance for credit losses (ACL) recognized under CECL or IFRS 9 accounting standards, representing expected credit losses on the loan portfolio."
    :param nonperforming_loans: "Loans that are in default or close to being in default, typically more than 90 days past due."
    :return: "Computed Coverage Ratio = Allowance for Credit Losses / Nonperforming Loans"
    '''
    return allowance_for_credit_losses / nonperforming_loans


def psa_prepayment_benchmark(month):
    '''
    domain: ['Structured finance & securitization']
    subdomain: ['Mortgage-Backed Securities', 'Prepayment Modeling']
    function: "PSA (Public Securities Association) Prepayment Benchmark is the standard prepayment model for mortgage-backed securities. At 100% PSA, the conditional prepayment rate (CPR) increases linearly from 0% to 6% over the first 30 months, then remains constant at 6% thereafter. The CPR at a given month equals min(0.06, 0.002 x month)."
    y_as_x: ['prepayment_speed_psa']
    :param month: "The seasoning month of the mortgage pool, starting from month 1."
    :return: "Computed CPR at 100% PSA = min(0.06, 0.002 x month)"
    '''
    return min(0.06, 0.002 * month)


def pti_payment_to_income(monthly_mortgage_payment, monthly_income):
    '''
    domain: ['Real estate finance & mortgages']
    subdomain: ['Mortgage Underwriting', 'Affordability Analysis']
    function: "PTI (Payment-to-Income) ratio measures the proportion of a borrower's monthly income consumed by the monthly mortgage payment. It is a key affordability metric used in mortgage underwriting to assess a borrower's ability to service the loan."
    y_as_x: []
    :param monthly_mortgage_payment: "The monthly mortgage payment including principal and interest."
    :param monthly_income: "The borrower's monthly income (gross or net, depending on the context)."
    :return: "Computed PTI = Monthly Mortgage Payment / Income"
    '''
    return monthly_mortgage_payment / monthly_income


def pti_payment_to_income_gross(monthly_loan_payment, gross_monthly_income):
    '''
    domain: ['Banking, consumer lending & project finance']
    subdomain: ['Consumer Lending', 'Mortgage Underwriting']
    function: "PTI (Payment-to-Income) ratio based on gross income measures the proportion of a borrower's gross monthly income consumed by the monthly loan payment. It is used by lenders to assess affordability and repayment capacity before taxes and deductions."
    y_as_x: []
    :param monthly_loan_payment: "The total monthly loan payment including principal and interest."
    :param gross_monthly_income: "The borrower's total monthly income before taxes and deductions."
    :return: "Computed PTI_gross = Monthly Loan Payment / Gross Monthly Income"
    '''
    return monthly_loan_payment / gross_monthly_income


def pti_payment_to_income_net(monthly_loan_payment, net_monthly_income):
    '''
    domain: ['Banking, consumer lending & project finance']
    subdomain: ['Consumer Lending', 'Mortgage Underwriting']
    function: "PTI (Payment-to-Income) ratio based on net income measures the proportion of a borrower's net monthly income consumed by the monthly loan payment. It provides a more conservative affordability assessment by using take-home pay."
    y_as_x: []
    :param monthly_loan_payment: "The total monthly loan payment including principal and interest."
    :param net_monthly_income: "The borrower's monthly income after taxes and deductions (take-home pay)."
    :return: "Computed PTI_net = Monthly Loan Payment / Net Monthly Income"
    '''
    return monthly_loan_payment / net_monthly_income


def public_market_equivalent_pme(distributions, capital_calls, public_index_returns):
    '''
    domain: ['Private equity, venture capital & LBO']
    subdomain: ['Performance Measurement', 'Benchmarking']
    function: "Public Market Equivalent (PME) compares the performance of a private equity fund to a public market index. It calculates the ratio of the future value of distributions (compounded at the public index return) to the future value of capital calls (compounded at the public index return). A PME greater than 1 indicates the fund outperformed the public market."
    y_as_x: ['pme_kaplan_schoar']
    :param distributions: "Array of periodic distributions (cash returned) from the private equity fund."
    :param capital_calls: "Array of periodic capital calls (cash invested) into the private equity fund."
    :param public_index_returns: "Array of periodic returns of the public market benchmark index, corresponding to the same periods as the cash flows."
    :return: "Computed PME = FV(distributions indexed to public benchmark) / FV(capital calls indexed to public benchmark)"
    '''
    distributions = np.array(distributions, dtype=float)
    capital_calls = np.array(capital_calls, dtype=float)
    public_index_returns = np.array(public_index_returns, dtype=float)
    n = len(distributions)
    # Compound each cash flow forward to the end using the public index
    fv_dist = 0.0
    fv_calls = 0.0
    for i in range(n):
        compound = np.prod(1 + public_index_returns[i + 1:]) if i + 1 < n else 1.0
        fv_dist += distributions[i] * compound
        fv_calls += capital_calls[i] * compound
    return fv_dist / fv_calls


def purchasing_power_parity_ppp(domestic_price_level, foreign_price_level):
    '''
    domain: ['FX & international finance']
    subdomain: ['Exchange Rate Theory', 'International Economics']
    function: "Purchasing Power Parity (PPP) theory states that the exchange rate between two currencies should equal the ratio of the two countries' price levels. Under absolute PPP, the equilibrium exchange rate S is determined by the ratio of domestic to foreign price levels."
    y_as_x: ['relative_ppp']
    :param domestic_price_level: "The domestic price level or price index (e.g., CPI) of the home country."
    :param foreign_price_level: "The foreign price level or price index of the foreign country."
    :return: "Computed PPP exchange rate S = P / P*"
    '''
    return domestic_price_level / foreign_price_level


def pure_endowment_apv(n, interest_rate, survival_prob_n):
    '''
    domain: ['Actuarial science & insurance']
    subdomain: ['Life Insurance', 'Actuarial Present Values']
    function: "Pure Endowment APV (Actuarial Present Value) calculates the expected present value of a payment of 1 made at time n, conditional on the insured being alive at that time. It equals the discount factor v^n multiplied by the n-year survival probability _np_x."
    y_as_x: ['endowment_insurance_apv']
    :param n: "The number of years until the endowment payment is due."
    :param interest_rate: "The annual effective interest rate used for discounting."
    :param survival_prob_n: "The probability that the insured person aged x survives n more years (_np_x)."
    :return: "Computed Pure Endowment APV = v^n * _np_x where v = 1/(1+i)"
    '''
    v = 1.0 / (1.0 + interest_rate)
    return (v ** n) * survival_prob_n


def pure_premium(frequency, severity):
    '''
    domain: ['Actuarial science & insurance']
    subdomain: ['Ratemaking', 'Loss Modeling']
    function: "Pure Premium (also known as the loss cost) is the expected loss per exposure unit, calculated as the product of claim frequency and average claim severity. It represents the minimum amount needed to cover expected losses before loading for expenses and profit."
    y_as_x: ['credibility_premium', 'gross_premium_principle']
    :param frequency: "The expected number of claims per exposure unit over the coverage period."
    :param severity: "The expected average cost per claim."
    :return: "Computed Pure Premium = Frequency x Severity"
    '''
    return frequency * severity


def put_payoff(S_T, K):
    '''
    domain: ['Derivatives, options & volatility']
    subdomain: ['Option Payoffs', 'Vanilla Options']
    function: "Put Payoff is the terminal payoff of a long put option at expiration. It equals the maximum of the difference between the strike price and the underlying asset price, or zero. The put option is in-the-money when the asset price is below the strike."
    y_as_x: ['protective_put_payoff', 'put_spread_payoff', 'straddle_payoff', 'strangle_payoff']
    :param S_T: "The price of the underlying asset at option expiration."
    :param K: "The strike price of the put option."
    :return: "Computed Put Payoff P_T = max(K - S_T, 0)"
    '''
    return np.maximum(K - S_T, 0)


def put_spread_payoff(S, K1, K2):
    '''
    domain: ['Derivatives, options & volatility']
    subdomain: ['Option Strategies', 'Spread Strategies']
    function: "Put Spread Payoff (Bear Put Spread) is the net payoff from buying a put at a higher strike K2 and selling a put at a lower strike K1. The maximum profit is K2 - K1 (when the asset price is below K1), and the maximum loss is the net premium paid."
    y_as_x: []
    :param S: "The price of the underlying asset at option expiration."
    :param K1: "The lower strike price of the short put option."
    :param K2: "The higher strike price of the long put option."
    :return: "Computed Put Spread Payoff = max(K2 - S, 0) - max(K1 - S, 0)"
    '''
    return np.maximum(K2 - S, 0) - np.maximum(K1 - S, 0)


def put_call_parity(S_0, K, r, T):
    '''
    domain: ['Derivatives, options & volatility']
    subdomain: ['Option Pricing Theory', 'Arbitrage Relations']
    function: "Put-Call Parity is a fundamental relationship between the prices of European call and put options with the same strike price and expiration. For a non-dividend-paying stock, C - P = S_0 - K*e^(-rT). This function returns the difference C - P implied by put-call parity."
    y_as_x: ['put_call_parity_equity', 'put_call_parity_futures_options']
    :param S_0: "The current spot price of the underlying asset."
    :param K: "The strike price of the options."
    :param r: "The risk-free interest rate (continuously compounded)."
    :param T: "The time to expiration in years."
    :return: "Computed C - P = S_0 - K * e^(-rT)"
    '''
    return S_0 - K * np.exp(-r * T)


def put_call_parity_equity(S_0, K, r, q, T):
    '''
    domain: ['Derivatives, options & volatility']
    subdomain: ['Option Pricing Theory', 'Equity Derivatives']
    function: "Put-Call Parity for equity options with continuous dividend yield q. The relationship becomes C - P = S_0*e^(-qT) - K*e^(-rT). This accounts for the present value of dividends foregone by holding the option rather than the stock."
    y_as_x: []
    :param S_0: "The current spot price of the underlying equity."
    :param K: "The strike price of the options."
    :param r: "The risk-free interest rate (continuously compounded)."
    :param q: "The continuous dividend yield on the underlying equity."
    :param T: "The time to expiration in years."
    :return: "Computed C - P = S_0 * e^(-qT) - K * e^(-rT)"
    '''
    return S_0 * np.exp(-q * T) - K * np.exp(-r * T)


def put_call_parity_futures_options(F_0, K, r, T):
    '''
    domain: ['Derivatives, options & volatility']
    subdomain: ['Option Pricing Theory', 'Futures Options']
    function: "Put-Call Parity for European options on futures contracts. The relationship is C - P = DF*(F_0 - K) where DF is the discount factor e^(-rT). This is derived from Black's model for futures options."
    y_as_x: []
    :param F_0: "The current futures price."
    :param K: "The strike price of the options."
    :param r: "The risk-free interest rate (continuously compounded)."
    :param T: "The time to expiration in years."
    :return: "Computed C - P = e^(-rT) * (F_0 - K)"
    '''
    return np.exp(-r * T) * (F_0 - K)


def pv_of_tax_shield(tax_shields, r_ts):
    '''
    domain: ['Corporate finance, valuation & capital budgeting']
    subdomain: ['Valuation', 'Tax Shield Analysis']
    function: "Present Value of Tax Shield computes the discounted value of future tax savings from interest expense deductibility. It is a key component in the Adjusted Present Value (APV) valuation approach, where the value of the levered firm equals the unlevered value plus the PV of tax shields."
    y_as_x: ['adjusted_present_value_apv']
    :param tax_shields: "An array of periodic tax shield amounts (Interest Expense x Tax Rate) for each future period."
    :param r_ts: "The discount rate appropriate for the tax shield cash flows. Often the cost of debt if the tax shield has the same risk as debt."
    :return: "Computed PV(Tax Shield) = sum_t Tax Shield_t / (1 + r_TS)^t"
    '''
    tax_shields = np.array(tax_shields, dtype=float)
    periods = np.arange(1, len(tax_shields) + 1)
    return np.sum(tax_shields / (1 + r_ts) ** periods)


def quadratic_program(P, q, G=None, h=None, A=None, b=None):
    '''
    domain: ['Quantitative forecasting & machine learning in finance']
    subdomain: ['Optimization', 'Convex Programming']
    function: "Quadratic Program solves the standard quadratic optimization problem: minimize 0.5*x'Px + q'x subject to inequality constraints Gx <= h and equality constraints Ax = b. It is fundamental to portfolio optimization, risk management, and many financial engineering applications."
    y_as_x: []
    :param P: "The positive semidefinite matrix defining the quadratic objective (n x n)."
    :param q: "The linear coefficient vector in the objective function (n x 1)."
    :param G: "The inequality constraint matrix (m x n). Optional."
    :param h: "The inequality constraint vector (m x 1). Optional."
    :param A: "The equality constraint matrix (p x n). Optional."
    :param b: "The equality constraint vector (p x 1). Optional."
    :return: "Optimal solution vector x that minimizes 0.5*x'Px + q'x subject to constraints"
    '''
    import cvxpy as cp
    n = P.shape[0]
    x = cp.Variable(n)
    objective = cp.Minimize(0.5 * cp.quad_form(x, P) + q @ x)
    constraints = []
    if G is not None and h is not None:
        constraints.append(G @ x <= h)
    if A is not None and b is not None:
        constraints.append(A @ x == b)
    prob = cp.Problem(objective, constraints)
    prob.solve()
    return x.value


def quick_ratio(cash, marketable_securities, accounts_receivable, current_liabilities):
    '''
    domain: ['Accounting & financial statement analysis']
    subdomain: ['Liquidity Analysis', 'Financial Ratios']
    function: "Quick Ratio (Acid-Test Ratio) measures a company's ability to meet its short-term obligations with its most liquid assets. Unlike the current ratio, it excludes inventory and prepaid expenses, providing a more conservative measure of liquidity."
    y_as_x: []
    :param cash: "Cash and cash equivalents held by the company."
    :param marketable_securities: "Short-term investments that can be quickly converted to cash at close to their market value."
    :param accounts_receivable: "Amounts owed to the company by customers for goods or services delivered on credit."
    :param current_liabilities: "Obligations due within one year, including accounts payable, short-term debt, and accrued expenses."
    :return: "Computed Quick Ratio = (Cash + Marketable Securities + AR) / Current Liabilities"
    '''
    return (cash + marketable_securities + accounts_receivable) / current_liabilities


def quoted_spread_pct(ask, bid):
    '''
    domain: ['Liquidity risk, market liquidity & execution cost']
    subdomain: ['Market Microstructure', 'Transaction Cost Analysis']
    function: "Quoted Spread (%) is the percentage difference between the ask and bid prices relative to the mid-price. It is a primary measure of the cost of immediacy in financial markets and reflects market maker compensation and liquidity conditions."
    y_as_x: ['relative_spread']
    :param ask: "The lowest price at which a seller is willing to sell the security."
    :param bid: "The highest price at which a buyer is willing to buy the security."
    :return: "Computed Quoted Spread (%) = (Ask - Bid) / Mid where Mid = (Ask + Bid) / 2"
    '''
    mid = (ask + bid) / 2.0
    return (ask - bid) / mid


def rate_of_change_roc(close, timeperiod=10):
    '''
    domain: ['Technical analysis & chart-based indicators']
    subdomain: ['Momentum Indicators']
    function: "Rate of Change (ROC) is a momentum oscillator that measures the percentage change in price between the current price and the price a specified number of periods ago. Positive ROC indicates upward momentum, negative ROC indicates downward momentum."
    y_as_x: []
    :param close: "Array or Series of closing prices."
    :param timeperiod: "The lookback period (number of periods) for the ROC calculation. Default is 10."
    :return: "Computed ROC = P_t / P_{t-n} - 1 (expressed as percentage)"
    '''
    import talib
    close = np.array(close, dtype=np.float64)
    return talib.ROC(close, timeperiod=timeperiod)


def real_estate_dcf(noi_series, terminal_value, discount_rate):
    '''
    domain: ['Real estate finance']
    subdomain: ['Property Valuation', 'Discounted Cash Flow']
    function: "Real Estate DCF (Discounted Cash Flow) values an income-producing property by discounting its projected net operating income (NOI) over the holding period and the terminal/reversion value at the end of the holding period. This is the fundamental income approach to real estate valuation."
    y_as_x: []
    :param noi_series: "Array of projected net operating income (NOI) for each period of the holding period."
    :param terminal_value: "The expected sale price or residual value of the property at the end of the holding period."
    :param discount_rate: "The discount rate (required rate of return) used to present-value the cash flows."
    :return: "Computed DCF Value = sum_t NOI_t/(1+r)^t + TV/(1+r)^T"
    '''
    import numpy_financial as npf
    noi_series = list(noi_series)
    noi_series[-1] = noi_series[-1] + terminal_value
    cash_flows = [0] + noi_series  # npv expects CF_0 at index 0
    return npf.npv(discount_rate, cash_flows)


def real_exchange_rate(nominal_rate, foreign_price_level, domestic_price_level):
    '''
    domain: ['FX & international finance']
    subdomain: ['Exchange Rate Analysis', 'International Economics']
    function: "Real Exchange Rate adjusts the nominal exchange rate for the relative price levels between two countries. It measures the purchasing power of one currency relative to another and is a key indicator of international competitiveness. An increase indicates real depreciation of the domestic currency."
    y_as_x: []
    :param nominal_rate: "The nominal exchange rate S (domestic currency per unit of foreign currency)."
    :param foreign_price_level: "The foreign country's price level or price index P*."
    :param domestic_price_level: "The domestic country's price level or price index P."
    :return: "Computed Real Exchange Rate q = S * P* / P"
    '''
    return nominal_rate * foreign_price_level / domestic_price_level


def real_yield_bond_pricing(real_cash_flows, real_yield):
    '''
    domain: ['Fixed income, bonds & credit markets']
    subdomain: ['Inflation-Linked Bonds', 'Bond Pricing']
    function: "Real Yield Bond Pricing values an inflation-linked bond (e.g., TIPS) by discounting its real cash flows at the real yield. The real cash flows are the coupon and principal payments in real (inflation-adjusted) terms."
    y_as_x: []
    :param real_cash_flows: "Array of real (inflation-adjusted) cash flows from the bond for each period."
    :param real_yield: "The real yield (yield adjusted for inflation) used to discount the cash flows."
    :return: "Computed bond price P = sum_t Real CF_t / (1 + real_y)^t"
    '''
    real_cash_flows = np.array(real_cash_flows, dtype=float)
    periods = np.arange(1, len(real_cash_flows) + 1)
    return np.sum(real_cash_flows / (1 + real_yield) ** periods)


def realized_beta(asset_returns_intraday, market_returns_intraday):
    '''
    domain: ['Market risk & volatility modeling']
    subdomain: ['Beta Estimation', 'High-Frequency Finance']
    function: "Realized Beta measures the sensitivity of an asset's returns to market returns using intraday (high-frequency) data. It is computed as the ratio of the realized covariance between the asset and the market to the realized variance of the market."
    y_as_x: []
    :param asset_returns_intraday: "Array of intraday returns of the asset."
    :param market_returns_intraday: "Array of intraday returns of the market index."
    :return: "Computed Realized Beta = Cov_intraday(asset, market) / Var_intraday(market)"
    '''
    asset_returns_intraday = np.array(asset_returns_intraday, dtype=float)
    market_returns_intraday = np.array(market_returns_intraday, dtype=float)
    cov = np.sum(asset_returns_intraday * market_returns_intraday)
    var_market = np.sum(market_returns_intraday ** 2)
    return cov / var_market


def realized_hedge_effectiveness(hedged_returns, unhedged_returns):
    '''
    domain: ['Commodities, futures & hedging']
    subdomain: ['Hedge Effectiveness', 'Risk Management']
    function: "Realized Hedge Effectiveness measures how much of the unhedged position's variance has been eliminated by the hedge. A value of 1 indicates a perfect hedge (all variance eliminated), while 0 indicates the hedge has no effect. Negative values indicate the hedge increased variance."
    y_as_x: []
    :param hedged_returns: "Array of returns on the hedged position (asset + hedge instrument)."
    :param unhedged_returns: "Array of returns on the unhedged position (asset only)."
    :return: "Computed HE = 1 - Var(Hedged Position) / Var(Unhedged Position)"
    '''
    return 1.0 - np.var(hedged_returns) / np.var(unhedged_returns)


def realized_spread(trade_price, mid_price_future, side):
    '''
    domain: ['Liquidity risk, market liquidity & execution cost']
    subdomain: ['Market Microstructure', 'Transaction Cost Analysis']
    function: "Realized Spread is a measure of market maker profitability that compares the trade price to the midpoint some time after the trade. It captures the actual revenue to the liquidity provider after adverse selection costs. A positive realized spread indicates compensation to the market maker."
    y_as_x: ['adverse_selection_cost']
    :param trade_price: "The price at which the trade was executed."
    :param mid_price_future: "The mid-price at time t+Delta (some time after the trade, e.g., 5 minutes)."
    :param side: "Trade direction indicator: +1 for buyer-initiated, -1 for seller-initiated."
    :return: "Computed Realized Spread = 2 * side * (Trade Price - Mid_{t+Delta})"
    '''
    return 2.0 * side * (trade_price - mid_price_future)


def realized_variance(intraday_returns):
    '''
    domain: ['Market risk & volatility modeling']
    subdomain: ['Volatility Estimation', 'High-Frequency Finance']
    function: "Realized Variance is a non-parametric estimator of the variance of asset returns over a given period, computed as the sum of squared intraday returns. It provides a model-free measure of ex-post volatility using high-frequency data."
    y_as_x: ['realized_volatility', 'bipower_variation', 'variance_swap_fair_strike']
    :param intraday_returns: "Array of intraday (high-frequency) log returns."
    :return: "Computed Realized Variance RV_t = sum_{i=1}^n r_{t,i}^2"
    '''
    intraday_returns = np.array(intraday_returns, dtype=float)
    return np.sum(intraday_returns ** 2)


def realized_volatility(intraday_returns):
    '''
    domain: ['Market risk & volatility modeling']
    subdomain: ['Volatility Estimation', 'High-Frequency Finance']
    function: "Realized Volatility is the square root of realized variance, providing an annualized or period-specific measure of actual price fluctuations based on high-frequency data. It is a model-free volatility estimator widely used for volatility forecasting and risk management."
    y_as_x: ['yang_zhang_volatility']
    :param intraday_returns: "Array of intraday (high-frequency) returns."
    :return: "Computed Realized Volatility RVOL = sqrt(sum of squared intraday returns)"
    '''
    intraday_returns = np.array(intraday_returns, dtype=float)
    return np.sqrt(np.sum(intraday_returns ** 2))


def receivables_turnover(revenue, average_accounts_receivable):
    '''
    domain: ['Accounting & financial statement analysis']
    subdomain: ['Efficiency Ratios', 'Working Capital Management']
    function: "Receivables Turnover measures how efficiently a company collects revenue from its credit customers. A higher ratio indicates faster collection of receivables. It is the inverse of the DSO (Days Sales Outstanding) when annualized."
    y_as_x: ['days_sales_outstanding_dso']
    :param revenue: "Total revenue (net sales) for the period."
    :param average_accounts_receivable: "The average accounts receivable balance during the period, typically (beginning AR + ending AR) / 2."
    :return: "Computed Receivables Turnover = Revenue / Average AR"
    '''
    return revenue / average_accounts_receivable


def recovery_factor(net_profit, maximum_drawdown):
    '''
    domain: ['Performance measurement & attribution']
    subdomain: ['Risk-Adjusted Performance', 'Trading Performance']
    function: "Recovery Factor measures the ratio of net profit to the absolute value of maximum drawdown. It indicates how many times the strategy's net profit exceeds its worst peak-to-trough decline. A higher recovery factor indicates better risk-adjusted performance."
    y_as_x: []
    :param net_profit: "The total net profit from the strategy or portfolio over the measurement period."
    :param maximum_drawdown: "The maximum drawdown (expressed as a positive value or absolute value) experienced during the period."
    :return: "Computed Recovery Factor = Net Profit / |Max Drawdown|"
    '''
    return net_profit / abs(maximum_drawdown)


def recovery_rate(loss_given_default):
    '''
    domain: ['Credit risk, default modeling & credit portfolio']
    subdomain: ['Loss Estimation', 'Credit Risk Parameters']
    function: "Recovery Rate is the percentage of the outstanding exposure that is recovered after a borrower defaults. It is the complement of the Loss Given Default (LGD), representing the proportion of the loan that the lender can expect to recover through collateral liquidation, guarantees, or other means."
    y_as_x: ['loss_given_default', 'reduced_form_cds_hazard_relation', 'cds_spread_approximation']
    :param loss_given_default: "Loss Given Default (LGD) is the proportion of the exposure that is lost if a borrower defaults, expressed as a decimal (e.g., 0.40 for 40%)."
    :return: "Computed Recovery Rate = 1 - LGD"
    '''
    return 1.0 - loss_given_default


def reduced_form_cds_hazard_relation(hazard_rate, loss_given_default):
    '''
    domain: ['Credit risk, default modeling & credit portfolio']
    subdomain: ['Credit Derivatives', 'Hazard Rate Modeling']
    function: "Reduced-Form CDS Hazard Relation is the approximation that relates the CDS spread to the hazard rate (default intensity) and Loss Given Default. Under the reduced-form framework, the CDS spread is approximately equal to the hazard rate multiplied by LGD."
    y_as_x: []
    :param hazard_rate: "The hazard rate (default intensity) lambda, representing the instantaneous probability of default per unit time."
    :param loss_given_default: "Loss Given Default (LGD), the fraction of exposure lost upon default."
    :return: "Computed CDS Spread approximation = lambda x LGD"
    '''
    return hazard_rate * loss_given_default


def refinance_proceeds(new_loan_amount, old_loan_balance, fees):
    '''
    domain: ['Real estate finance & mortgages']
    subdomain: ['Mortgage Refinancing', 'Consumer Lending']
    function: "Refinance Proceeds calculates the net cash available to the borrower after refinancing. It equals the new loan amount minus the payoff of the old loan balance minus all refinancing fees and closing costs."
    y_as_x: []
    :param new_loan_amount: "The principal amount of the new refinanced loan."
    :param old_loan_balance: "The remaining balance on the existing loan being refinanced."
    :param fees: "Total refinancing costs including origination fees, appraisal fees, title fees, and other closing costs."
    :return: "Computed Refinance Proceeds = New Loan - Old Loan - Fees"
    '''
    return new_loan_amount - old_loan_balance - fees


def relative_ppp(domestic_inflation, foreign_inflation):
    '''
    domain: ['FX & international finance']
    subdomain: ['Exchange Rate Theory', 'International Economics']
    function: "Relative Purchasing Power Parity predicts that the change in the exchange rate will approximately equal the inflation differential between two countries. If the domestic inflation exceeds the foreign inflation, the domestic currency is expected to depreciate."
    y_as_x: []
    :param domestic_inflation: "The domestic inflation rate (pi_d) over the period."
    :param foreign_inflation: "The foreign inflation rate (pi_f) over the period."
    :return: "Computed expected exchange rate change Delta S / S = pi_d - pi_f"
    '''
    return domestic_inflation - foreign_inflation


def relative_spread(ask, bid):
    '''
    domain: ['Liquidity risk & market liquidity']
    subdomain: ['Market Microstructure', 'Spread Analysis']
    function: "Relative Spread measures the bid-ask spread as a proportion of the mid-price. It is equivalent to the quoted spread percentage and provides a normalized measure of trading costs that is comparable across securities with different price levels."
    y_as_x: []
    :param ask: "The lowest price at which a seller is willing to sell the security."
    :param bid: "The highest price at which a buyer is willing to buy the security."
    :return: "Computed Relative Spread = (Ask - Bid) / Mid where Mid = (Ask + Bid) / 2"
    '''
    mid = (ask + bid) / 2.0
    return (ask - bid) / mid


def relative_strength_index_rsi(close, timeperiod=14):
    '''
    domain: ['Technical analysis & chart-based indicators']
    subdomain: ['Momentum Indicators', 'Overbought/Oversold']
    function: "Relative Strength Index (RSI) is a momentum oscillator that measures the speed and magnitude of recent price changes to evaluate overbought or oversold conditions. RSI ranges from 0 to 100, with readings above 70 indicating overbought conditions and below 30 indicating oversold conditions."
    y_as_x: ['stochastic_rsi']
    :param close: "Array or Series of closing prices."
    :param timeperiod: "The lookback period for the RSI calculation. Default is 14."
    :return: "Computed RSI = 100 - 100/(1+RS) where RS = AvgGain / AvgLoss"
    '''
    import talib
    close = np.array(close, dtype=np.float64)
    return talib.RSI(close, timeperiod=timeperiod)


def rent_coverage_ratio(gross_monthly_income, monthly_rent):
    '''
    domain: ['Real estate finance & mortgages']
    subdomain: ['Rental Affordability', 'Tenant Screening']
    function: "Rent Coverage Ratio measures a tenant's ability to pay rent by comparing their gross monthly income to the monthly rent. A higher ratio indicates greater ability to afford the rent. Landlords typically require a ratio of at least 2.5 to 3.0."
    y_as_x: []
    :param gross_monthly_income: "The tenant's total gross monthly income before taxes and deductions."
    :param monthly_rent: "The monthly rent payment required."
    :return: "Computed Rent Coverage = Gross Monthly Income / Monthly Rent"
    '''
    return gross_monthly_income / monthly_rent


def repricing_gap(rate_sensitive_assets, rate_sensitive_liabilities):
    '''
    domain: ['Treasury, ALM & balance-sheet management']
    subdomain: ['Interest Rate Risk', 'Asset-Liability Management']
    function: "Repricing Gap measures the difference between rate-sensitive assets and rate-sensitive liabilities in a given time bucket. A positive gap means more assets than liabilities reprice in that period, making the bank's net interest income benefit from rising rates."
    y_as_x: ['cumulative_gap']
    :param rate_sensitive_assets: "The total value of assets that will reprice (have their interest rates reset) within the time bucket."
    :param rate_sensitive_liabilities: "The total value of liabilities that will reprice within the time bucket."
    :return: "Computed Gap_t = Rate Sensitive Assets_t - Rate Sensitive Liabilities_t"
    '''
    return rate_sensitive_assets - rate_sensitive_liabilities


def residual_income(net_income, cost_of_equity, beginning_equity):
    '''
    domain: ['Corporate finance, valuation & capital budgeting']
    subdomain: ['Performance Measurement', 'Value-Based Management']
    function: "Residual Income measures the economic profit earned by a firm or division above the required return on equity. It is the net income minus the equity charge (cost of equity multiplied by the beginning book equity). Positive residual income indicates value creation."
    y_as_x: ['residual_income_valuation']
    :param net_income: "Net Income is the total profit after all expenses, taxes, and interest have been deducted from revenue."
    :param cost_of_equity: "The required rate of return on equity (R_e), representing the minimum return shareholders expect."
    :param beginning_equity: "The book value of equity at the beginning of the period."
    :return: "Computed Residual Income RI = Net Income - R_e x Beginning Equity"
    '''
    return net_income - cost_of_equity * beginning_equity


def residual_income_valuation(book_value_0, residual_incomes, discount_rate):
    '''
    domain: ['Equity valuation & asset pricing']
    subdomain: ['Intrinsic Valuation', 'Residual Income Model']
    function: "Residual Income Valuation estimates the intrinsic value of a stock as the current book value plus the present value of expected future residual incomes. This model is particularly useful when dividends are unpredictable and links accounting data to intrinsic value."
    y_as_x: []
    :param book_value_0: "The current book value per share (B_0)."
    :param residual_incomes: "Array of projected residual income values for each future period."
    :param discount_rate: "The cost of equity used to discount future residual incomes."
    :return: "Computed V_0 = B_0 + sum_t RI_t / (1+r)^t"
    '''
    residual_incomes = np.array(residual_incomes, dtype=float)
    periods = np.arange(1, len(residual_incomes) + 1)
    pv_ri = np.sum(residual_incomes / (1 + discount_rate) ** periods)
    return book_value_0 + pv_ri


def retention_ratio(dividend_payout_ratio):
    '''
    domain: ['Accounting & financial statement analysis']
    subdomain: ['Dividend Policy', 'Growth Analysis']
    function: "Retention Ratio (Plowback Ratio) measures the proportion of net income retained by the company rather than distributed as dividends. It is a key input to the sustainable growth rate calculation (g = ROE x Retention Ratio)."
    y_as_x: ['sustainable_growth_rate']
    :param dividend_payout_ratio: "Dividend Payout Ratio is the proportion of net income paid out as dividends, expressed as a decimal."
    :return: "Computed Retention Ratio = 1 - Dividend Payout Ratio"
    '''
    return 1.0 - dividend_payout_ratio


def retrospective_reserve(accumulated_premiums, accumulated_benefits, accumulated_expenses):
    '''
    domain: ['Actuarial science & insurance']
    subdomain: ['Life Insurance Reserving', 'Policy Values']
    function: "Retrospective Reserve calculates the policy reserve at time t by looking backward at the accumulated value of past premiums received minus the accumulated value of past benefits paid and expenses incurred. Under standard actuarial assumptions, it equals the prospective reserve."
    y_as_x: []
    :param accumulated_premiums: "The accumulated (future) value at time t of all premiums received up to time t."
    :param accumulated_benefits: "The accumulated (future) value at time t of all benefits paid up to time t."
    :param accumulated_expenses: "The accumulated (future) value at time t of all expenses incurred up to time t."
    :return: "Computed Retrospective Reserve V_t = Accumulated Value(Past Premiums - Past Benefits - Expenses)"
    '''
    return accumulated_premiums - accumulated_benefits - accumulated_expenses


def return_on_assets_roa(net_income, average_assets):
    '''
    domain: ['Accounting & financial statement analysis']
    subdomain: ['Profitability Ratios', 'Financial Statement Analysis']
    function: "Return on Assets (ROA) measures how efficiently a company uses its assets to generate profit. It indicates the percentage of profit earned relative to total assets, showing management effectiveness in deploying the company's asset base."
    y_as_x: ['piotroski_f_score']
    :param net_income: "Net Income is the total profit after all expenses, taxes, and interest have been deducted from revenue."
    :param average_assets: "The average total assets during the period, typically (beginning assets + ending assets) / 2."
    :return: "Computed ROA = Net Income / Average Assets"
    '''
    return net_income / average_assets


def return_on_capital_employed_roce(ebit, capital_employed):
    '''
    domain: ['Accounting & financial statement analysis']
    subdomain: ['Profitability Ratios', 'Capital Efficiency']
    function: "Return on Capital Employed (ROCE) measures the profitability and efficiency with which a company's capital is deployed. It uses EBIT (not net income) to provide a pre-tax, pre-interest perspective on returns, making it useful for comparing companies with different capital structures."
    y_as_x: []
    :param ebit: "EBIT (Earnings Before Interest and Taxes) measures a company's profitability from core operations."
    :param capital_employed: "Capital Employed is the total capital invested in the business, typically Total Assets - Current Liabilities, or Equity + Long-term Debt."
    :return: "Computed ROCE = EBIT / Capital Employed"
    '''
    return ebit / capital_employed


def return_on_equity_roe(net_income, average_equity):
    '''
    domain: ['Accounting & financial statement analysis']
    subdomain: ['Profitability Ratios', 'Shareholder Returns']
    function: "Return on Equity (ROE) measures the return generated on shareholders' equity investment. It is one of the most important profitability metrics, indicating how effectively management uses equity capital to generate profits. It is also a key input to the DuPont decomposition and sustainable growth rate."
    y_as_x: ['sustainable_growth_rate', 'residual_income']
    :param net_income: "Net Income is the total profit after all expenses, taxes, and interest have been deducted from revenue."
    :param average_equity: "The average shareholders' equity during the period, typically (beginning equity + ending equity) / 2."
    :return: "Computed ROE = Net Income / Average Equity"
    '''
    return net_income / average_equity


def return_on_invested_capital_roic(nopat, average_invested_capital):
    '''
    domain: ['Accounting & financial statement analysis']
    subdomain: ['Profitability Ratios', 'Capital Efficiency']
    function: "Return on Invested Capital (ROIC) measures how efficiently a company generates returns on the total capital invested by both equity and debt holders. It uses NOPAT (Net Operating Profit After Tax) to provide a tax-adjusted but capital-structure-neutral profitability measure."
    y_as_x: []
    :param nopat: "NOPAT (Net Operating Profit After Tax) = EBIT x (1 - Tax Rate). It represents the after-tax operating profit available to all capital providers."
    :param average_invested_capital: "Average Invested Capital is the average total capital invested in the business (Equity + Debt - Excess Cash), typically averaged over the period."
    :return: "Computed ROIC = NOPAT / Average Invested Capital"
    '''
    return nopat / average_invested_capital


def return_on_regulatory_capital_rorc(expected_profit, regulatory_capital):
    '''
    domain: ['Banking, consumer lending & project finance']
    subdomain: ['Bank Performance', 'Capital Management']
    function: "Return on Regulatory Capital (RORC) measures the profitability of a banking activity relative to the regulatory or economic capital allocated to it. It is used to assess whether a business line generates sufficient returns to justify the capital consumed."
    y_as_x: []
    :param expected_profit: "The expected profit or net income generated by the business activity."
    :param regulatory_capital: "The regulatory or economic capital allocated to support the business activity."
    :return: "Computed RORC = Expected Profit / Regulatory Capital"
    '''
    return expected_profit / regulatory_capital


def revenue_growth(revenue_current, revenue_previous):
    '''
    domain: ['Accounting & financial statement analysis']
    subdomain: ['Growth Analysis', 'Financial Statement Analysis']
    function: "Revenue Growth measures the percentage change in a company's revenue from one period to the next. It is a fundamental indicator of a company's top-line momentum and market demand for its products or services."
    y_as_x: []
    :param revenue_current: "Revenue in the current period (Revenue_t)."
    :param revenue_previous: "Revenue in the previous period (Revenue_{t-1})."
    :return: "Computed Revenue Growth g_t = Revenue_t / Revenue_{t-1} - 1"
    '''
    return revenue_current / revenue_previous - 1.0


def rho(K, T, r, d2_value, option_type='call'):
    '''
    domain: ['Derivatives, options & volatility']
    subdomain: ['Option Greeks', 'Risk Sensitivities']
    function: "Rho measures the sensitivity of an option's price to changes in the risk-free interest rate. For a European call, Rho = K*T*e^(-rT)*N(d2), and for a European put, Rho = -K*T*e^(-rT)*N(-d2). It is typically the smallest of the major Greeks."
    y_as_x: []
    :param K: "The strike price of the option."
    :param T: "The time to expiration in years."
    :param r: "The risk-free interest rate (continuously compounded)."
    :param d2_value: "The d2 value from the Black-Scholes-Merton formula."
    :param option_type: "Option type: 'call' or 'put'. Default is 'call'."
    :return: "Computed Rho for call = K * T * e^(-rT) * N(d2); for put = -K * T * e^(-rT) * N(-d2)"
    '''
    from scipy.stats import norm
    if option_type == 'call':
        return K * T * np.exp(-r * T) * norm.cdf(d2_value)
    else:
        return -K * T * np.exp(-r * T) * norm.cdf(-d2_value)


def risk_parity_objective(returns, cov_matrix=None):
    '''
    domain: ['Asset management & portfolio optimization']
    subdomain: ['Portfolio Construction', 'Risk Budgeting']
    function: "Risk Parity Objective seeks portfolio weights such that each asset contributes equally to the total portfolio risk. The optimization minimizes the sum of squared differences between risk contributions across all asset pairs. This approach avoids concentration risk and produces more diversified portfolios."
    y_as_x: ['equal_risk_contribution']
    :param returns: "DataFrame or array of asset returns used to estimate the covariance matrix."
    :param cov_matrix: "The covariance matrix of asset returns. If None, it will be estimated from returns."
    :return: "Optimal portfolio weights achieving equal risk contribution"
    '''
    import riskfolio as rp
    returns = pd.DataFrame(returns)
    port = rp.Portfolio(returns=returns)
    if cov_matrix is not None:
        port.cov = cov_matrix
    else:
        port.assets_stats(method_mu='hist', method_cov='hist')
    weights = port.rp_optimization(model='Classic', rm='MV', hist=True)
    return weights


def riskmetrics_covariance(returns, decay_factor=0.94):
    '''
    domain: ['Market risk & volatility modeling']
    subdomain: ['Covariance Estimation', 'EWMA Models']
    function: "RiskMetrics Covariance uses the exponentially weighted moving average (EWMA) approach to estimate the time-varying covariance matrix. The decay factor (lambda) controls the rate at which older observations lose influence. The standard RiskMetrics value is lambda = 0.94 for daily data."
    y_as_x: []
    :param returns: "DataFrame or 2D array of asset returns (T x N) where T is the number of observations and N is the number of assets."
    :param decay_factor: "The EWMA decay factor lambda. Default is 0.94 (RiskMetrics daily)."
    :return: "Computed time-varying covariance matrix Sigma_t = lambda * Sigma_{t-1} + (1-lambda) * r_{t-1} * r_{t-1}'"
    '''
    returns = np.array(returns, dtype=float)
    T, N = returns.shape
    cov = np.outer(returns[0], returns[0])
    for t in range(1, T):
        cov = decay_factor * cov + (1 - decay_factor) * np.outer(returns[t], returns[t])
    return cov


def risk_neutral_probability(r, q, dt, u, d):
    '''
    domain: ['Derivatives, options & volatility']
    subdomain: ['Binomial Trees', 'Option Pricing']
    function: "Risk-Neutral Probability is the probability used in the binomial option pricing model to discount expected payoffs at the risk-free rate. It ensures the expected return on the underlying asset under the risk-neutral measure equals the risk-free rate minus the dividend yield."
    y_as_x: ['binomial_option_pricing', 'american_option_binomial_pricing']
    :param r: "The risk-free interest rate (continuously compounded)."
    :param q: "The continuous dividend yield on the underlying asset."
    :param dt: "The length of each time step in the binomial tree (Delta t)."
    :param u: "The up factor in the binomial tree."
    :param d: "The down factor in the binomial tree."
    :return: "Computed risk-neutral probability p = (e^{(r-q)*dt} - d) / (u - d)"
    '''
    return (np.exp((r - q) * dt) - d) / (u - d)


def risk_weighted_assets_rwa(exposures, risk_weights):
    '''
    domain: ['Bank regulation, Basel & prudential ratios']
    subdomain: ['Capital Adequacy', 'Basel Framework']
    function: "Risk-Weighted Assets (RWA) is the total of all assets held by a bank weighted by their credit risk according to regulatory guidelines. RWA is the denominator in key capital adequacy ratios (CET1, Tier 1, Total Capital). Assets with higher risk receive higher weights."
    y_as_x: ['cet1_ratio', 'tier_1_capital_ratio', 'total_capital_ratio', 'basel_standardized_capital_requirement', 'mrel_over_tlac_ratio', 'stress_capital_buffer']
    :param exposures: "Array of exposure amounts for each asset class or credit exposure."
    :param risk_weights: "Array of regulatory risk weights corresponding to each exposure (e.g., 0% for sovereign, 20% for banks, 100% for corporate)."
    :return: "Computed RWA = sum_i Exposure_i x RiskWeight_i"
    '''
    exposures = np.array(exposures, dtype=float)
    risk_weights = np.array(risk_weights, dtype=float)
    return np.sum(exposures * risk_weights)


def roc_auc(y_true, y_score):
    '''
    domain: ['Quantitative forecasting & machine learning in finance']
    subdomain: ['Model Evaluation', 'Classification Metrics']
    function: "ROC AUC (Area Under the Receiver Operating Characteristic Curve) measures the ability of a binary classifier to distinguish between positive and negative classes. AUC ranges from 0 to 1, where 1 indicates perfect classification and 0.5 indicates no discriminative power (random guessing). It is widely used in credit scoring and default prediction."
    y_as_x: []
    :param y_true: "Array of true binary labels (0 or 1)."
    :param y_score: "Array of predicted probabilities or scores for the positive class."
    :return: "Computed AUC = area under the ROC curve"
    '''
    from sklearn.metrics import roc_auc_score
    return roc_auc_score(y_true, y_score)


def rogers_satchell_volatility(high, low, open_price, close):
    '''
    domain: ['Market risk & volatility modeling']
    subdomain: ['Volatility Estimation', 'Range-Based Estimators']
    function: "Rogers-Satchell Volatility is a range-based volatility estimator that uses open, high, low, and close prices. Unlike Parkinson or Garman-Klass, it does not assume a zero drift, making it more accurate for trending markets. It remains unbiased in the presence of a non-zero mean return."
    y_as_x: ['yang_zhang_volatility']
    :param high: "Array of high prices for each period."
    :param low: "Array of low prices for each period."
    :param open_price: "Array of opening prices for each period."
    :param close: "Array of closing prices for each period."
    :return: "Computed Rogers-Satchell variance sigma_RS^2 = mean of (ln(H/O)*ln(H/C) + ln(L/O)*ln(L/C))"
    '''
    high = np.array(high, dtype=float)
    low = np.array(low, dtype=float)
    open_price = np.array(open_price, dtype=float)
    close = np.array(close, dtype=float)
    rs = np.log(high / open_price) * np.log(high / close) + np.log(low / open_price) * np.log(low / close)
    return np.sqrt(np.mean(rs))


def roll_implied_spread(prices):
    '''
    domain: ['Liquidity risk, market liquidity & execution cost']
    subdomain: ['Market Microstructure', 'Spread Estimation']
    function: "Roll Implied Spread estimates the effective bid-ask spread from transaction price data alone, without requiring quote data. It exploits the negative serial covariance induced by the bid-ask bounce: the spread equals 2 times the square root of the negative autocovariance of price changes."
    y_as_x: []
    :param prices: "Array or Series of transaction prices."
    :return: "Computed Roll Spread = 2 * sqrt(-Cov(Delta p_t, Delta p_{t-1})) if covariance is negative, else 0"
    '''
    prices = np.array(prices, dtype=float)
    dp = np.diff(prices)
    cov = np.cov(dp[1:], dp[:-1])[0, 1]
    if cov < 0:
        return 2.0 * np.sqrt(-cov)
    else:
        return 0.0


def roll_rate(balance_migrating_worse, prior_bucket_balance):
    '''
    domain: ['Credit risk, default modeling & credit portfolio']
    subdomain: ['Delinquency Analysis', 'Credit Risk Monitoring']
    function: "Roll Rate measures the proportion of loan balances that migrate from one delinquency bucket to a worse one over a given period. It is a key input for estimating future defaults and losses in consumer lending and structured finance. Higher roll rates indicate deteriorating credit quality."
    y_as_x: []
    :param balance_migrating_worse: "The total balance of loans that migrated to a worse delinquency bucket during the period."
    :param prior_bucket_balance: "The total balance of loans in the prior (better) delinquency bucket at the beginning of the period."
    :return: "Computed Roll Rate = balances migrating to worse bucket / prior bucket balance"
    '''
    return balance_migrating_worse / prior_bucket_balance


def roll_spread_estimator(prices):
    '''
    domain: ['Liquidity risk & market liquidity']
    subdomain: ['Market Microstructure', 'Spread Estimation']
    function: "Roll Spread Estimator estimates the effective bid-ask spread from the serial covariance of price changes. It is based on the model where observed price changes alternate between bid and ask prices. The estimator equals 2*sqrt(-Cov(DP_t, DP_{t-1}))."
    y_as_x: []
    :param prices: "Array or Series of transaction prices."
    :return: "Computed Roll Spread = 2 * sqrt(-Cov(DeltaP_t, DeltaP_{t-1})) if covariance is negative, else 0"
    '''
    prices = np.array(prices, dtype=float)
    dp = np.diff(prices)
    cov = np.cov(dp[1:], dp[:-1])[0, 1]
    if cov < 0:
        return 2.0 * np.sqrt(-cov)
    else:
        return 0.0


def roll_yield(futures_return, spot_return, collateral_return):
    '''
    domain: ['Commodities, futures & hedging']
    subdomain: ['Commodity Returns', 'Futures Roll']
    function: "Roll Yield is the component of commodity futures return attributable to the rolling of futures contracts. In backwardated markets, roll yield is positive as the investor buys cheaper near-month contracts and rolls into more expensive far-month contracts. It is calculated as the residual after subtracting spot and collateral returns."
    y_as_x: ['commodity_carry_return']
    :param futures_return: "The total return from the futures position."
    :param spot_return: "The return from changes in the spot price of the commodity."
    :param collateral_return: "The return earned on the collateral posted for the futures position (typically the risk-free rate)."
    :return: "Computed Roll Yield = Futures Return - Spot Return - Collateral Return"
    '''
    return futures_return - spot_return - collateral_return


def roll_down_return(duration, delta_yield):
    '''
    domain: ['Fixed income, bonds & credit markets']
    subdomain: ['Bond Return Attribution', 'Yield Curve Strategies']
    function: "Roll-Down Return estimates the price return on a bond from the passage of time as it 'rolls down' the yield curve toward maturity. As a bond's remaining maturity shortens, it typically moves to a lower yield on an upward-sloping curve, generating a positive return. It is approximated as the negative of duration times the yield change from the curve slide."
    y_as_x: ['bond_carry_and_roll', 'yield_curve_carry']
    :param duration: "The modified duration of the bond, measuring price sensitivity to yield changes."
    :param delta_yield: "The change in yield (negative if rolling down a normal curve) from the curve slide."
    :return: "Computed Roll-Down Return approximation = -Duration x Delta Yield from curve slide"
    '''
    return -duration * delta_yield


def rsi(close, window=14):
    '''
    domain: ['Technical analysis']
    subdomain: ['Momentum Indicators', 'Overbought/Oversold']
    function: "RSI (Relative Strength Index) is a momentum oscillator measuring the speed and change of price movements. It oscillates between 0 and 100, with values above 70 typically indicating overbought conditions and below 30 indicating oversold conditions."
    y_as_x: ['stochastic_rsi']
    :param close: "Array or Series of closing prices."
    :param window: "The lookback window for the RSI calculation. Default is 14."
    :return: "Computed RSI = 100 - 100/(1 + RS) where RS = AvgGain/AvgLoss"
    '''
    import talib
    close = np.array(close, dtype=np.float64)
    return talib.RSI(close, timeperiod=window)


def rvpi(residual_value_nav, paid_in_capital):
    '''
    domain: ['Private equity, venture capital & LBO']
    subdomain: ['Fund Performance', 'Unrealized Returns']
    function: "RVPI (Residual Value to Paid-In Capital) measures the ratio of a fund's remaining (unrealized) net asset value to the total capital invested. It represents the unrealized portion of a fund's total value and, combined with DPI, equals TVPI."
    y_as_x: ['tvpi']
    :param residual_value_nav: "The current net asset value (NAV) of the fund's unrealized investments."
    :param paid_in_capital: "The total capital contributed (called) by limited partners to the fund."
    :return: "Computed RVPI = Residual Value (NAV) / Paid-In Capital"
    '''
    return residual_value_nav / paid_in_capital


def sabr_implied_vol(F, K, T, alpha, beta, rho_param, nu):
    '''
    domain: ['Derivatives, options & volatility']
    subdomain: ['Volatility Surface', 'Stochastic Volatility']
    function: "SABR Implied Volatility computes the Black-Scholes implied volatility using the SABR (Stochastic Alpha Beta Rho) model. The SABR model is widely used in interest rate and FX markets to capture the volatility smile/skew. It parameterizes the dynamics of the forward rate and its volatility."
    y_as_x: ['local_over_stochastic_volatility_surface_interpolation']
    :param F: "The forward price of the underlying asset."
    :param K: "The strike price of the option."
    :param T: "The time to expiration in years."
    :param alpha: "The initial (ATM) volatility parameter of the SABR model."
    :param beta: "The elasticity parameter (0 <= beta <= 1). Beta=0 gives normal model, beta=1 gives lognormal."
    :param rho_param: "The correlation between the forward rate and its volatility (-1 < rho < 1)."
    :param nu: "The volatility of volatility (vol-of-vol) parameter."
    :return: "Computed SABR implied Black-Scholes volatility sigma_BS"
    '''
    # Hagan et al. SABR approximation formula
    if abs(F - K) < 1e-12:
        # ATM case
        FK_mid = F
        logFK = 0.0
        z = 0.0
        x_z = 1.0
    else:
        FK_mid = (F * K) ** ((1 - beta) / 2.0)
        logFK = np.log(F / K)
        z = (nu / alpha) * FK_mid * logFK
        x_z = np.log((np.sqrt(1 - 2 * rho_param * z + z ** 2) + z - rho_param) / (1 - rho_param))
        if abs(x_z) < 1e-12:
            x_z = 1.0
        else:
            x_z = z / x_z

    term1 = alpha / (FK_mid * (1 + ((1 - beta) ** 2 / 24.0) * logFK ** 2 +
                                ((1 - beta) ** 4 / 1920.0) * logFK ** 4))
    term2 = 1 + ((((1 - beta) ** 2 / 24.0) * alpha ** 2 / (FK_mid ** 2)) +
                  (0.25 * rho_param * beta * nu * alpha / FK_mid) +
                  ((2 - 3 * rho_param ** 2) / 24.0) * nu ** 2) * T

    return term1 * x_z * term2


def sarima(endog, order=(1, 0, 0), seasonal_order=(1, 0, 0, 12)):
    '''
    domain: ['Econometrics & time-series finance']
    subdomain: ['Time Series Modeling', 'Forecasting']
    function: "SARIMA (Seasonal AutoRegressive Integrated Moving Average) extends ARIMA to handle seasonal patterns in time series data. It includes both non-seasonal (p,d,q) and seasonal (P,D,Q,s) components, where s is the seasonal period. It is widely used for forecasting financial and economic time series with seasonal behavior."
    y_as_x: []
    :param endog: "The endogenous time series data (array or Series) to be modeled."
    :param order: "Tuple (p,d,q) specifying the non-seasonal ARIMA order."
    :param seasonal_order: "Tuple (P,D,Q,s) specifying the seasonal ARIMA order and seasonal period."
    :return: "Fitted SARIMAX model results object"
    '''
    from statsmodels.tsa.statespace.sarimax import SARIMAX
    model = SARIMAX(endog, order=order, seasonal_order=seasonal_order,
                    enforce_stationarity=False, enforce_invertibility=False)
    results = model.fit(disp=False)
    return results


def security_market_line(risk_free_rate, beta, expected_market_return):
    '''
    domain: ['Equity valuation & asset pricing']
    subdomain: ['Capital Asset Pricing Model', 'Expected Returns']
    function: "Security Market Line (SML) represents the CAPM relationship graphically, plotting expected return against systematic risk (beta). Any security plotting above the SML is undervalued (positive alpha), and below it is overvalued (negative alpha). The equation is the same as CAPM."
    y_as_x: ['capm_expected_return', 'alpha']
    :param risk_free_rate: "The risk-free rate of return (R_f), typically the yield on government bonds."
    :param beta: "The systematic risk (beta) of the security, measuring its sensitivity to market movements."
    :param expected_market_return: "The expected return of the market portfolio E[R_m]."
    :return: "Computed E[R] = R_f + beta * (E[R_m] - R_f)"
    '''
    return risk_free_rate + beta * (expected_market_return - risk_free_rate)


def selection_effect_brinson_fachler(benchmark_weights, portfolio_returns, benchmark_returns):
    '''
    domain: ['Performance measurement & attribution']
    subdomain: ['Performance Attribution', 'Brinson Model']
    function: "Selection Effect (Brinson-Fachler) measures the value added by the portfolio manager's security selection within each sector. It captures the return impact of choosing different securities within a sector compared to the benchmark, weighted by the benchmark's sector allocation."
    y_as_x: []
    :param benchmark_weights: "Array of benchmark weights for each sector (w_i^B)."
    :param portfolio_returns: "Array of portfolio returns for each sector (r_i^P)."
    :param benchmark_returns: "Array of benchmark returns for each sector (r_i^B)."
    :return: "Computed Selection Effect per sector = w_i^B * (r_i^P - r_i^B)"
    '''
    benchmark_weights = np.array(benchmark_weights, dtype=float)
    portfolio_returns = np.array(portfolio_returns, dtype=float)
    benchmark_returns = np.array(benchmark_returns, dtype=float)
    return benchmark_weights * (portfolio_returns - benchmark_returns)


def semivariance(returns, target=0.0):
    '''
    domain: ['Market risk & volatility modeling']
    subdomain: ['Downside Risk', 'Risk Measurement']
    function: "Semivariance measures the dispersion of returns that fall below a target or threshold (typically the mean or zero). Unlike variance, which penalizes both upside and downside deviations equally, semivariance focuses only on downside risk, making it more relevant for risk-averse investors."
    y_as_x: ['sortino_ratio', 'downside_deviation']
    :param returns: "Array or Series of returns."
    :param target: "The target or minimum acceptable return (MAR). Default is 0."
    :return: "Computed SemiVariance = E[min(R - target, 0)^2]"
    '''
    returns = np.array(returns, dtype=float)
    downside = np.minimum(returns - target, 0)
    return np.mean(downside ** 2)


def severity(net_loss, defaulted_balance):
    '''
    domain: ['Structured finance & securitization']
    subdomain: ['Loss Analysis', 'Credit Risk']
    function: "Severity (Loss Severity) measures the proportion of the defaulted loan balance that is actually lost after recovery efforts. It is synonymous with Loss Given Default (LGD) in the context of structured finance and securitization."
    y_as_x: ['pure_premium']
    :param net_loss: "The net loss amount after all recoveries have been applied to the defaulted loan."
    :param defaulted_balance: "The outstanding balance of the loan at the time of default."
    :return: "Computed Severity = Net Loss / Defaulted Balance"
    '''
    return net_loss / defaulted_balance


def sharpe_ratio(returns, risk_free_rate=0.0):
    '''
    domain: ['Asset management & portfolio optimization']
    subdomain: ['Risk-Adjusted Performance', 'Portfolio Evaluation']
    function: "Sharpe Ratio measures the excess return per unit of total risk (standard deviation). It is the most widely used risk-adjusted performance measure, allowing investors to compare the return premium relative to total volatility. A higher Sharpe ratio indicates better risk-adjusted returns."
    y_as_x: ['m_squared_modigliani', 'maximum_sharpe_portfolio', 'appraisal_ratio']
    :param returns: "Array or Series of periodic portfolio returns."
    :param risk_free_rate: "The risk-free rate per period (same frequency as returns). Default is 0."
    :return: "Computed Sharpe Ratio = (E[R_p] - R_f) / sigma_p"
    '''
    import empyrical
    returns = pd.Series(returns)
    return empyrical.sharpe_ratio(returns, risk_free=risk_free_rate)


def sharpe_lintner_beta_regression(portfolio_excess_returns, market_excess_returns):
    '''
    domain: ['Equity valuation & asset pricing']
    subdomain: ['Factor Models', 'Beta Estimation']
    function: "Sharpe-Lintner Beta Regression estimates the CAPM beta and alpha by regressing the portfolio's excess returns on the market's excess returns. The slope coefficient is the estimated beta, and the intercept is Jensen's alpha, measuring the portfolio's risk-adjusted abnormal return."
    y_as_x: ['alpha_from_regression']
    :param portfolio_excess_returns: "Array of portfolio excess returns (R_p - R_f) for each period."
    :param market_excess_returns: "Array of market excess returns (R_m - R_f) for each period."
    :return: "Fitted OLS regression results with alpha (intercept) and beta (slope)"
    '''
    import statsmodels.api as sm
    X = sm.add_constant(market_excess_returns)
    model = sm.OLS(portfolio_excess_returns, X)
    results = model.fit()
    return results


def short_rate_bond_pricing_pde(r_0, kappa, theta, sigma, T, n_steps=100, n_grid=100):
    '''
    domain: ['Interest-rate modeling & term structures']
    subdomain: ['PDE Methods', 'Bond Pricing']
    function: "Short-Rate Bond Pricing PDE solves the partial differential equation for bond pricing under a short-rate model: dP/dt + a(r,t)*dP/dr + 0.5*b(r,t)^2*d^2P/dr^2 - r*P = 0, with boundary condition P(T,r)=1. This is the fundamental PDE for pricing zero-coupon bonds under any affine short-rate model."
    y_as_x: []
    :param r_0: "The current (initial) short rate."
    :param kappa: "The mean-reversion speed parameter."
    :param theta: "The long-run mean of the short rate."
    :param sigma: "The volatility parameter of the short rate."
    :param T: "The maturity of the bond in years."
    :param n_steps: "Number of time steps for the finite difference grid."
    :param n_grid: "Number of spatial grid points for the rate dimension."
    :return: "Computed bond price P(0, T) from PDE solution"
    '''
    # Use Vasicek closed-form as PDE solution for dr = kappa(theta-r)dt + sigma dW
    B = (1 - np.exp(-kappa * T)) / kappa
    A = np.exp((theta - sigma ** 2 / (2 * kappa ** 2)) * (B - T) - (sigma ** 2 / (4 * kappa)) * B ** 2)
    return A * np.exp(-B * r_0)


def simple_compounding(pv, r, t):
    '''
    domain: ['Interest-rate modeling & term structures']
    subdomain: ['Interest Rate Conventions', 'Time Value of Money']
    function: "Simple Compounding calculates the future value under simple interest, where interest is not compounded. The future value equals the present value multiplied by (1 + rate x time). This convention is commonly used for money market instruments with maturities less than one year."
    y_as_x: ['continuous_compounding']
    :param pv: "The present value or initial principal amount."
    :param r: "The simple interest rate (annualized)."
    :param t: "The time period in years (or fraction thereof)."
    :return: "Computed FV = PV * (1 + r * t)"
    '''
    return pv * (1 + r * t)


def simple_forward_rate(discount_factor_T, tau):
    '''
    domain: ['Interest-rate modeling & term structures']
    subdomain: ['Forward Rates', 'Discount Factors']
    function: "Simple Forward Rate computes the simply-compounded forward rate from a discount factor and the year fraction. Given a discount factor DF(T), the simple forward rate F is derived from 1 + F*tau = 1/DF(T), solving for F."
    y_as_x: ['fra_rate']
    :param discount_factor_T: "The discount factor for the period DF(T)."
    :param tau: "The year fraction (day count fraction) for the period."
    :return: "Computed Simple Forward Rate F = (1/DF(T) - 1) / tau"
    '''
    return (1.0 / discount_factor_T - 1.0) / tau


def simple_return(price_current, price_previous):
    '''
    domain: ['Performance measurement & attribution']
    subdomain: ['Return Calculation', 'Performance Measurement']
    function: "Simple Return (arithmetic return) measures the percentage change in the price of an asset from one period to the next. It is the most intuitive return measure and is additive across assets in a portfolio but not across time."
    y_as_x: ['cumulative_return', 'log_return', 'portfolio_return', 'holding_period_return_hpr']
    :param price_current: "The price of the asset at the end of the current period (P_t)."
    :param price_previous: "The price of the asset at the end of the previous period (P_{t-1})."
    :return: "Computed Simple Return R_t = P_t / P_{t-1} - 1"
    '''
    return price_current / price_previous - 1.0


def single_monthly_mortality_smm(cpr):
    '''
    domain: ['Structured finance & securitization']
    subdomain: ['Prepayment Analysis', 'Mortgage-Backed Securities']
    function: "Single Monthly Mortality (SMM) converts the annual Conditional Prepayment Rate (CPR) to a monthly prepayment rate. It represents the fraction of the mortgage pool that prepays in a single month. The relationship is SMM = 1 - (1 - CPR)^(1/12)."
    y_as_x: ['conditional_prepayment_rate_cpr', 'conditional_prepayment_rate_cpr_v2']
    :param cpr: "The annual Conditional Prepayment Rate (CPR), expressed as a decimal."
    :return: "Computed SMM = 1 - (1 - CPR)^(1/12)"
    '''
    return 1.0 - (1.0 - cpr) ** (1.0 / 12.0)


def slippage(actual_execution_price, expected_price):
    '''
    domain: ['Liquidity risk, market liquidity & execution cost']
    subdomain: ['Execution Cost', 'Trading Performance']
    function: "Slippage measures the difference between the actual execution price and the expected or target price at the time a trade order is placed. Positive slippage indicates a worse execution for the trader. It is a key component of total transaction costs."
    y_as_x: ['implementation_shortfall', 'arrival_price_slippage']
    :param actual_execution_price: "The actual price at which the trade was executed."
    :param expected_price: "The expected or target price at the time the trade decision was made (e.g., the mid-price or decision price)."
    :return: "Computed Slippage = Actual Execution Price - Expected Price"
    '''
    return actual_execution_price - expected_price


def smith_wilson_extrapolation(maturities, discount_factors, ufr, alpha):
    '''
    domain: ['Interest-rate modeling & term structures']
    subdomain: ['Yield Curve Extrapolation', 'Solvency II']
    function: "Smith-Wilson Extrapolation is a method used to extrapolate the yield curve beyond the last liquid point toward the Ultimate Forward Rate (UFR). It is mandated under Solvency II for insurance companies. The method ensures a smooth transition from observed market rates to the long-term equilibrium rate."
    y_as_x: []
    :param maturities: "Array of observed maturities (in years) for the liquid instruments."
    :param discount_factors: "Array of observed discount factors corresponding to the maturities."
    :param ufr: "The Ultimate Forward Rate (UFR), the long-term equilibrium forward rate."
    :param alpha: "The convergence speed parameter controlling how quickly rates converge to the UFR."
    :return: "Smith-Wilson fitted discount factor function coefficients (zeta vector)"
    '''
    maturities = np.array(maturities, dtype=float)
    discount_factors = np.array(discount_factors, dtype=float)
    n = len(maturities)

    # Wilson function W(u, v)
    def wilson_func(u, v, ufr_val, alpha_val):
        return np.exp(-ufr_val * (u + v)) * (
            alpha_val * np.minimum(u, v) -
            0.5 * np.exp(-alpha_val * np.maximum(u, v)) * (
                np.exp(alpha_val * np.minimum(u, v)) - np.exp(-alpha_val * np.minimum(u, v))
            )
        )

    # Build the W matrix
    W = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            W[i, j] = wilson_func(maturities[i], maturities[j], ufr, alpha)

    # mu = e^{-UFR * u}
    mu = np.exp(-ufr * maturities)

    # Solve for zeta: W * zeta = DF - mu
    zeta = np.linalg.solve(W, discount_factors - mu)
    return zeta


def solvency_ratio(available_capital, required_capital):
    '''
    domain: ['Actuarial science & insurance']
    subdomain: ['Insurance Regulation', 'Solvency Assessment']
    function: "Solvency Ratio measures the adequacy of an insurer's capital relative to its regulatory capital requirement. A ratio above 100% indicates the insurer has surplus capital above the minimum required. It is a key metric under Solvency II and other insurance regulatory frameworks."
    y_as_x: []
    :param available_capital: "The insurer's available capital (own funds) eligible to cover regulatory requirements."
    :param required_capital: "The required capital (e.g., Solvency Capital Requirement under Solvency II)."
    :return: "Computed Solvency Ratio = Available Capital / Required Capital"
    '''
    return available_capital / required_capital


def sortino_ratio(returns, required_return=0.0):
    '''
    domain: ['Asset management & portfolio optimization']
    subdomain: ['Risk-Adjusted Performance', 'Downside Risk']
    function: "Sortino Ratio measures excess return per unit of downside risk, using downside deviation instead of total standard deviation. Unlike the Sharpe ratio, it only penalizes returns below a minimum acceptable return (MAR), making it more appropriate for investors who are only concerned about downside risk."
    y_as_x: []
    :param returns: "Array or Series of periodic portfolio returns."
    :param required_return: "The minimum acceptable return (MAR) per period. Default is 0."
    :return: "Computed Sortino Ratio = (E[R_p] - MAR) / Downside Deviation"
    '''
    import empyrical
    returns = pd.Series(returns)
    return empyrical.sortino_ratio(returns, required_return=required_return)


def sources_and_uses_balance(total_sources, total_uses):
    '''
    domain: ['Private equity, venture capital & LBO']
    subdomain: ['LBO Modeling', 'Transaction Structuring']
    function: "Sources and Uses Balance verifies that total financing sources equal total transaction uses in an LBO or M&A transaction. Sources include equity, debt, and rollover equity; uses include purchase price, transaction fees, and debt refinancing. The balance must hold for the transaction to close."
    y_as_x: []
    :param total_sources: "Total financing sources (equity + debt + existing cash + rollover)."
    :param total_uses: "Total transaction uses (purchase price + fees + debt payoff + other costs)."
    :return: "Boolean indicating whether Total Sources = Total Uses (within tolerance)"
    '''
    return np.isclose(total_sources, total_uses)


def spark_spread(electricity_price, heat_rate, fuel_price):
    '''
    domain: ['Commodities, futures & hedging']
    subdomain: ['Energy Markets', 'Power Generation']
    function: "Spark Spread measures the theoretical gross margin of a gas-fired power plant by comparing the price of electricity output to the cost of natural gas input (adjusted by the heat rate). A positive spark spread indicates it is profitable to run the plant."
    y_as_x: []
    :param electricity_price: "The market price of electricity (per MWh)."
    :param heat_rate: "The heat rate of the power plant, measuring fuel efficiency (MMBtu per MWh)."
    :param fuel_price: "The price of natural gas fuel (per MMBtu)."
    :return: "Computed Spark Spread = Electricity Price - Heat Rate x Fuel Price"
    '''
    return electricity_price - heat_rate * fuel_price


def speed(S, K, T, r, sigma, q=0.0):
    '''
    domain: ['Derivatives, options & volatility']
    subdomain: ['Option Greeks', 'Higher-Order Sensitivities']
    function: "Speed (DgammaDspot) is the third derivative of the option price with respect to the underlying asset price, or equivalently the rate of change of gamma with respect to the spot price. It measures how gamma will change as the underlying moves and is important for managing gamma risk in options portfolios."
    y_as_x: []
    :param S: "The current price of the underlying asset."
    :param K: "The strike price of the option."
    :param T: "The time to expiration in years."
    :param r: "The risk-free interest rate (continuously compounded)."
    :param sigma: "The volatility of the underlying asset."
    :param q: "The continuous dividend yield. Default is 0."
    :return: "Computed Speed = d(Gamma)/dS"
    '''
    from scipy.stats import norm
    d1 = (np.log(S / K) + (r - q + 0.5 * sigma ** 2) * T) / (sigma * np.sqrt(T))
    gamma_val = np.exp(-q * T) * norm.pdf(d1) / (S * sigma * np.sqrt(T))
    speed_val = -gamma_val / S * (d1 / (sigma * np.sqrt(T)) + 1)
    return speed_val


def sponsor_cash_on_cash_return(cumulative_cash_to_sponsor, sponsor_equity_invested):
    '''
    domain: ['Private equity, venture capital & LBO']
    subdomain: ['Fund Performance', 'Cash Returns']
    function: "Sponsor Cash-on-Cash Return measures the total cash distributions received by the private equity sponsor relative to the equity capital invested. It is a simple multiple-of-money metric that indicates the total cash return without considering the time value of money."
    y_as_x: []
    :param cumulative_cash_to_sponsor: "Total cumulative cash distributions received by the sponsor, including dividends, recaps, and exit proceeds."
    :param sponsor_equity_invested: "The total equity capital invested by the sponsor in the deal."
    :return: "Computed Cash-on-Cash = Cumulative Cash to Sponsor / Sponsor Equity Invested"
    '''
    return cumulative_cash_to_sponsor / sponsor_equity_invested


def spot_rate_bootstrapping(bond_prices, coupon_rates, face_value=100, frequency=2):
    '''
    domain: ['Fixed income, bonds & credit markets']
    subdomain: ['Yield Curve Construction', 'Bootstrapping']
    function: "Spot Rate Bootstrapping derives the zero-coupon (spot) yield curve from observed coupon bond prices. Starting from the shortest maturity, each successive spot rate is determined by using previously derived discount factors to solve for the unknown discount factor at the new maturity."
    y_as_x: ['nelson_siegel_yield_curve', 'nelson_siegel_svensson_curve']
    :param bond_prices: "Array of observed clean prices for bonds of increasing maturity."
    :param coupon_rates: "Array of annual coupon rates for each bond (as decimals)."
    :param face_value: "The face value of the bonds. Default is 100."
    :param frequency: "The coupon payment frequency per year. Default is 2 (semi-annual)."
    :return: "Array of bootstrapped spot rates for each maturity"
    '''
    n = len(bond_prices)
    spot_rates = np.zeros(n)
    discount_factors = np.zeros(n)

    for i in range(n):
        coupon = coupon_rates[i] * face_value / frequency
        t = (i + 1) / frequency
        # Sum of PV of known coupons
        pv_known = 0
        for j in range(i):
            pv_known += coupon * discount_factors[j]
        # Solve for DF_i: P = pv_known + (coupon + face_value) * DF_i
        discount_factors[i] = (bond_prices[i] - pv_known) / (coupon + face_value)
        spot_rates[i] = (1.0 / discount_factors[i]) ** (1.0 / t) - 1.0

    return spot_rates


def spot_rate_from_discount_factor(discount_factor, t):
    '''
    domain: ['Fixed income & bond math']
    subdomain: ['Yield Curve Mathematics', 'Discount Factors']
    function: "Spot Rate from Discount Factor derives the continuously compounded zero-coupon (spot) rate from a discount factor and its corresponding maturity. The spot rate z(t) = -ln(DF(t))/t represents the annualized continuously compounded return for a zero-coupon investment maturing at time t."
    y_as_x: ['forward_rate', 'forward_rate_from_spot_rates']
    :param discount_factor: "The discount factor DF(t) for maturity t."
    :param t: "The time to maturity in years."
    :return: "Computed Spot Rate z(t) = -ln(DF(t)) / t"
    '''
    return -np.log(discount_factor) / t


def spread_duration(bond_price, bond_price_up, bond_price_down, spread_shift):
    '''
    domain: ['Fixed income, bonds & credit markets']
    subdomain: ['Credit Risk Sensitivity', 'Spread Analysis']
    function: "Spread Duration measures the sensitivity of a bond's price to a change in its credit spread. It quantifies the approximate percentage price change for a one basis point change in the spread. It is particularly important for corporate bonds and credit products."
    y_as_x: ['duration_times_spread_dts']
    :param bond_price: "The current price of the bond P."
    :param bond_price_up: "The bond price when the spread is increased by the spread_shift."
    :param bond_price_down: "The bond price when the spread is decreased by the spread_shift."
    :param spread_shift: "The parallel shift in spread used for the calculation (e.g., 0.0001 for 1bp)."
    :return: "Computed Spread Duration = -(P_up - P_down) / (2 * P * spread_shift)"
    '''
    return -(bond_price_up - bond_price_down) / (2.0 * bond_price * spread_shift)


def spread_option_kirk_approximation(F1, F2, K, T, r, sigma1, sigma2, rho_param):
    '''
    domain: ['Derivatives, options & volatility']
    subdomain: ['Exotic Options', 'Spread Options']
    function: "Spread Option (Kirk Approximation) values a European call option on the spread between two assets using Kirk's closed-form approximation. It approximates the spread option price using a modified Black-Scholes formula, treating the option as a single-asset option with an adjusted volatility."
    y_as_x: []
    :param F1: "The forward price of the first (long) asset."
    :param F2: "The forward price of the second (short) asset."
    :param K: "The strike price of the spread option."
    :param T: "The time to expiration in years."
    :param r: "The risk-free interest rate (continuously compounded)."
    :param sigma1: "The volatility of the first asset."
    :param sigma2: "The volatility of the second asset."
    :param rho_param: "The correlation between the two asset returns."
    :return: "Computed spread call option price using Kirk's approximation"
    '''
    from scipy.stats import norm
    DF = np.exp(-r * T)
    F2_adj = F2 + K
    sigma_adj = np.sqrt(sigma1 ** 2 - 2 * rho_param * sigma1 * sigma2 * (F2 / F2_adj) +
                        (sigma2 * F2 / F2_adj) ** 2)
    d1 = (np.log(F1 / F2_adj) + 0.5 * sigma_adj ** 2 * T) / (sigma_adj * np.sqrt(T))
    d2 = d1 - sigma_adj * np.sqrt(T)
    return DF * (F1 * norm.cdf(d1) - F2_adj * norm.cdf(d2))


def square_root_impact_law(Y, sigma, Q, V):
    '''
    domain: ['Liquidity risk, market liquidity & execution cost']
    subdomain: ['Market Impact', 'Execution Cost Modeling']
    function: "Square-Root Impact Law is an empirical market impact model that states the price impact of a trade is proportional to the volatility times the square root of the ratio of order size to average daily volume. The constant Y is typically calibrated to be around 1. This concave relationship is widely observed across different markets."
    y_as_x: []
    :param Y: "The impact coefficient (typically calibrated, often around 1)."
    :param sigma: "The daily volatility of the asset."
    :param Q: "The order size (number of shares or notional)."
    :param V: "The average daily volume."
    :return: "Computed Impact = Y * sigma * sqrt(Q/V)"
    '''
    return Y * sigma * np.sqrt(Q / V)


def stable_funding_gap(required_stable_funding, available_stable_funding):
    '''
    domain: ['Treasury, ALM & balance-sheet management']
    subdomain: ['Liquidity Management', 'NSFR']
    function: "Stable Funding Gap measures the difference between required stable funding and available stable funding. A positive gap indicates a funding shortfall that the institution needs to address. It is closely related to the Net Stable Funding Ratio (NSFR) requirement."
    y_as_x: []
    :param required_stable_funding: "The amount of stable funding required based on the liquidity characteristics and maturity of assets."
    :param available_stable_funding: "The amount of stable funding available from equity, long-term debt, and stable deposits."
    :return: "Computed Stable Funding Gap = Required Stable Funding - Available Stable Funding"
    '''
    return required_stable_funding - available_stable_funding


def state_space_measurement_equation(Z, alpha, epsilon_cov=None, n_obs=None):
    '''
    domain: ['Econometrics & time-series finance']
    subdomain: ['State-Space Models', 'Kalman Filter']
    function: "State-Space Measurement Equation defines the relationship between the observed data y_t and the unobserved state vector alpha_t: y_t = Z_t * alpha_t + epsilon_t. The measurement matrix Z maps the latent state to the observable variables, and epsilon_t is the observation noise."
    y_as_x: []
    :param Z: "The measurement (observation) matrix mapping states to observations (n_obs x n_states)."
    :param alpha: "The state vector alpha_t (n_states x 1)."
    :param epsilon_cov: "The covariance matrix of the observation noise epsilon_t. If None, returns the deterministic part."
    :param n_obs: "Number of observations to simulate. If None, returns a single observation."
    :return: "Computed observation y_t = Z * alpha_t + epsilon_t"
    '''
    Z = np.array(Z, dtype=float)
    alpha = np.array(alpha, dtype=float)
    y = Z @ alpha
    if epsilon_cov is not None:
        epsilon = np.random.multivariate_normal(np.zeros(Z.shape[0]), np.array(epsilon_cov))
        y = y + epsilon
    return y


def state_space_transition_equation(T_mat, alpha, R=None, eta_cov=None):
    '''
    domain: ['Econometrics & time-series finance']
    subdomain: ['State-Space Models', 'Kalman Filter']
    function: "State-Space Transition Equation defines how the latent state vector evolves over time: alpha_{t+1} = T_t * alpha_t + R_t * eta_t. The transition matrix T governs the state dynamics, and R*eta represents the state noise."
    y_as_x: []
    :param T_mat: "The transition matrix T_t (n_states x n_states) governing state dynamics."
    :param alpha: "The current state vector alpha_t (n_states x 1)."
    :param R: "The selection matrix R_t for the state noise (n_states x n_shocks). If None, assumed identity."
    :param eta_cov: "The covariance matrix of the state noise eta_t. If None, returns the deterministic part."
    :return: "Computed next state alpha_{t+1} = T * alpha_t + R * eta_t"
    '''
    T_mat = np.array(T_mat, dtype=float)
    alpha = np.array(alpha, dtype=float)
    alpha_next = T_mat @ alpha
    if R is not None and eta_cov is not None:
        R = np.array(R, dtype=float)
        n_shocks = R.shape[1]
        eta = np.random.multivariate_normal(np.zeros(n_shocks), np.array(eta_cov))
        alpha_next = alpha_next + R @ eta
    return alpha_next


def sterling_ratio(returns):
    '''
    domain: ['Asset management & portfolio optimization']
    subdomain: ['Risk-Adjusted Performance', 'Drawdown-Based Metrics']
    function: "Sterling Ratio measures risk-adjusted return by dividing the compound annual growth rate (CAGR) by the average drawdown. It is similar to the Calmar ratio but uses average drawdown rather than maximum drawdown, providing a more stable measure of downside risk."
    y_as_x: []
    :param returns: "Array or Series of periodic portfolio returns."
    :return: "Computed Sterling Ratio = CAGR / Average Drawdown"
    '''
    import quantstats as qs
    returns = pd.Series(returns)
    return qs.stats.sterling(returns)


def stochastic_oscillator(high, low, close, fastk_period=14, slowk_period=3, slowd_period=3):
    '''
    domain: ['Technical analysis']
    subdomain: ['Momentum Indicators', 'Overbought/Oversold']
    function: "Stochastic Oscillator is a momentum indicator comparing a security's closing price to its price range over a given period. %K measures the current close relative to the high-low range, and %D is a moving average of %K. Values above 80 suggest overbought conditions; below 20 suggest oversold."
    y_as_x: []
    :param high: "Array of high prices."
    :param low: "Array of low prices."
    :param close: "Array of closing prices."
    :param fastk_period: "The lookback period for %K. Default is 14."
    :param slowk_period: "The smoothing period for slow %K. Default is 3."
    :param slowd_period: "The smoothing period for %D. Default is 3."
    :return: "Tuple of (slowk, slowd) arrays representing the Stochastic Oscillator %K and %D values"
    '''
    import talib
    high = np.array(high, dtype=np.float64)
    low = np.array(low, dtype=np.float64)
    close = np.array(close, dtype=np.float64)
    slowk, slowd = talib.STOCH(high, low, close,
                                fastk_period=fastk_period,
                                slowk_period=slowk_period,
                                slowk_matype=0,
                                slowd_period=slowd_period,
                                slowd_matype=0)
    return slowk, slowd


def stochastic_oscillator_pctd(high, low, close, fastk_period=14, slowk_period=3, slowd_period=3):
    '''
    domain: ['Technical analysis & chart-based indicators']
    subdomain: ['Momentum Indicators', 'Stochastic Analysis']
    function: "Stochastic Oscillator %D is the signal line of the stochastic oscillator, computed as a 3-period simple moving average of %K. It provides a smoothed version of the raw stochastic reading and is used for generating buy/sell signals when it crosses %K."
    y_as_x: []
    :param high: "Array of high prices."
    :param low: "Array of low prices."
    :param close: "Array of closing prices."
    :param fastk_period: "The lookback period for %K. Default is 14."
    :param slowk_period: "The smoothing period for slow %K. Default is 3."
    :param slowd_period: "The smoothing period for %D. Default is 3."
    :return: "Computed %D = SMA_3(%K)"
    '''
    import talib
    high = np.array(high, dtype=np.float64)
    low = np.array(low, dtype=np.float64)
    close = np.array(close, dtype=np.float64)
    _, slowd = talib.STOCH(high, low, close,
                           fastk_period=fastk_period,
                           slowk_period=slowk_period,
                           slowk_matype=0,
                           slowd_period=slowd_period,
                           slowd_matype=0)
    return slowd


def stochastic_oscillator_pctk(high, low, close, fastk_period=14, slowk_period=3):
    '''
    domain: ['Technical analysis & chart-based indicators']
    subdomain: ['Momentum Indicators', 'Stochastic Analysis']
    function: "Stochastic Oscillator %K measures where the closing price sits within the recent high-low range. Raw %K = 100 * (Close - Low_n) / (High_n - Low_n). The slow %K is a smoothed version. Values near 100 indicate the price is near the top of its range."
    y_as_x: ['stochastic_oscillator_pctd']
    :param high: "Array of high prices."
    :param low: "Array of low prices."
    :param close: "Array of closing prices."
    :param fastk_period: "The lookback period for the raw %K. Default is 14."
    :param slowk_period: "The smoothing period for slow %K. Default is 3."
    :return: "Computed %K = 100 * (C - L_n) / (H_n - L_n)"
    '''
    import talib
    high = np.array(high, dtype=np.float64)
    low = np.array(low, dtype=np.float64)
    close = np.array(close, dtype=np.float64)
    slowk, _ = talib.STOCH(high, low, close,
                           fastk_period=fastk_period,
                           slowk_period=slowk_period,
                           slowk_matype=0,
                           slowd_period=3,
                           slowd_matype=0)
    return slowk


def stochastic_rsi(close, timeperiod=14, fastk_period=5, fastd_period=3):
    '''
    domain: ['Technical analysis & chart-based indicators']
    subdomain: ['Momentum Indicators', 'Overbought/Oversold']
    function: "Stochastic RSI applies the Stochastic Oscillator formula to RSI values instead of price data. It ranges from 0 to 1 and provides a more sensitive indicator of overbought/oversold conditions than standard RSI. StochRSI = (RSI - min RSI_n) / (max RSI_n - min RSI_n)."
    y_as_x: []
    :param close: "Array or Series of closing prices."
    :param timeperiod: "The lookback period for the RSI calculation. Default is 14."
    :param fastk_period: "The lookback period for the stochastic %K of RSI. Default is 5."
    :param fastd_period: "The smoothing period for the stochastic %D of RSI. Default is 3."
    :return: "Computed StochRSI = (RSI - min RSI_n) / (max RSI_n - min RSI_n)"
    '''
    import talib
    close = np.array(close, dtype=np.float64)
    rsi_values = talib.RSI(close, timeperiod=timeperiod)
    # Compute stochastic of RSI manually
    result = np.full_like(rsi_values, np.nan)
    for i in range(fastk_period - 1 + timeperiod, len(rsi_values)):
        window = rsi_values[i - fastk_period + 1:i + 1]
        if np.all(~np.isnan(window)):
            min_rsi = np.nanmin(window)
            max_rsi = np.nanmax(window)
            if max_rsi - min_rsi > 0:
                result[i] = (rsi_values[i] - min_rsi) / (max_rsi - min_rsi)
            else:
                result[i] = 0.5
    return result
